# Generated by Django 4.2.3 on 2024-02-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(max_length=4),
        ),
    ]
