# Generated by Django 4.2.3 on 2024-02-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0003_alter_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
