# Generated by Django 4.2.3 on 2024-02-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0005_contact_time_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
