# Generated by Django 4.2.10 on 2024-02-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0010_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
