# Generated by Django 4.2.10 on 2024-02-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0014_add_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shooper_app.product'),
        ),
    ]
