# Generated by Django 4.2.10 on 2024-02-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0015_add_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shooper_app.login'),
        ),
    ]
