# Generated by Django 4.2.10 on 2024-02-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0018_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
