# Generated by Django 4.2.10 on 2024-02-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0019_abc_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABC',
        ),
    ]
