# Generated by Django 4.2.10 on 2024-02-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0021_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='address0',
        ),
    ]
