# Generated by Django 4.2.10 on 2024-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0024_alter_order1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order1',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
