# Generated by Django 4.0.3 on 2024-03-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0029_order1_order_id_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order1',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
