# Generated by Django 4.0.3 on 2024-03-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0030_alter_order1_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order1',
        ),
    ]
