# Generated by Django 4.0.3 on 2024-04-05 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0033_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='shooper_app.main_category'),
        ),
    ]
