# Generated by Django 4.0.3 on 2024-04-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0035_remove_product_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count', to='shooper_app.sub_category'),
        ),
    ]
