# Generated by Django 4.0.3 on 2024-04-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0040_rename_address_user_address1_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order1',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shooper_app.product'),
        ),
    ]
