# Generated by Django 4.0.3 on 2024-04-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0041_order1_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order1',
            name='order_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
