# Generated by Django 4.0.3 on 2024-04-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0042_alter_order1_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order1',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='shooper_app.product'),
        ),
    ]
