# Generated by Django 4.0.3 on 2024-04-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0044_remove_order1_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order1',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='shooper_app.product'),
        ),
    ]
