# Generated by Django 4.0.3 on 2024-04-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0045_order1_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('review', models.TextField(max_length=500)),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
