# Generated by Django 4.0.3 on 2024-04-20 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0046_review_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_details',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shooper_app.product'),
        ),
    ]
