# Generated by Django 4.0.3 on 2024-04-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0047_review_details_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='size_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
    ]
